import {initializeApp} from 'https://www.gstatic.com/firebasejs/12.0.0/firebase-app.js';
import {getFirestore,collection,doc,getDoc,getDocs,setDoc,addDoc,updateDoc,deleteDoc,onSnapshot,writeBatch,query,orderBy,limit} from 'https://www.gstatic.com/firebasejs/12.0.0/firebase-firestore.js';

const firebaseConfig={apiKey:'AIzaSyBIG5j_8pHr5C1KlFuG6lG0WunlUR8EJFs',authDomain:'tiebreak-opstelling.firebaseapp.com',projectId:'tiebreak-opstelling',storageBucket:'tiebreak-opstelling.firebasestorage.app',messagingSenderId:'363554771251',appId:'1:363554771251:web:811ab3b99099fe4b1dee46'};
const app=initializeApp(firebaseConfig),db=getFirestore(app);
const $=id=>document.getElementById(id);
const APP_URL='https://tiebreak-opstelling.netlify.app';
let players=[],responses={},evenings={},field={playing:[],reserve:[]},currentSchedule=null,importRows=[];

function esc(v=''){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function iso(d){return d.toISOString().slice(0,10)}
function localDate(s){return new Intl.DateTimeFormat('nl-NL',{weekday:'long',day:'numeric',month:'long',year:'numeric'}).format(new Date(s+'T12:00:00'))}
function upcomingTuesdays(){const now=new Date(),cut=new Date(now);cut.setHours(21,0,0,0);let offset=(2-now.getDay()+7)%7;if(offset===0&&now>=cut)offset=7;const first=new Date(now);first.setDate(now.getDate()+offset);return [first,new Date(first.getFullYear(),first.getMonth(),first.getDate()+7)].map(iso)}
function fullName(p){return `${p.firstName||''} ${p.lastName||''}`.trim()}
function displayName(p){const sameFirst=players.filter(x=>(x.firstName||'').toLowerCase()===(p.firstName||'').toLowerCase());if(sameFirst.length===1)return p.firstName||fullName(p);const sameFull=players.filter(x=>fullName(x).toLowerCase()===fullName(p).toLowerCase());return sameFull.length===1?fullName(p):`${fullName(p)} (nr. ${p.number||'-'})`}
function playerById(id){return players.find(p=>p.id===id)}
function toast(t){const e=document.createElement('div');e.className='toast';e.textContent=t;document.body.append(e);setTimeout(()=>e.remove(),2300)}
async function log(action,details=''){await addDoc(collection(db,'logs'),{action,details,at:new Date().toISOString()}).catch(()=>{})}

function initTabs(){document.querySelectorAll('.tabs button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tabs button').forEach(x=>x.classList.toggle('active',x===b));document.querySelectorAll('.panel').forEach(x=>x.classList.toggle('active',x.id===b.dataset.tab));if(b.dataset.tab==='organizer')renderOrganizer();});}
function renderDates(){const dates=upcomingTuesdays();$('orgDate').innerHTML=dates.map(d=>`<option value="${d}">${localDate(d)}</option>`).join('');renderParticipantDates();loadOrganizerDate();}

onSnapshot(collection(db,'players'),snap=>{players=snap.docs.map(d=>({id:d.id,...d.data()})).sort((a,b)=>(a.number||999)-(b.number||999));renderPlayers();renderParticipantSelect();renderParticipantDates();renderOrganizer();});

function renderParticipantSelect(){const old=$('participantSelect').value;$('participantSelect').innerHTML='<option value="">Kies je naam</option>'+players.map(p=>`<option value="${p.id}">${esc(displayName(p))}</option>`).join('');if(players.some(p=>p.id===old))$('participantSelect').value=old;updateProfileHint();}
$('participantSelect').onchange=()=>{localStorage.setItem('selectedPlayer',$('participantSelect').value);updateProfileHint();renderParticipantDates()};
function updateProfileHint(){const p=playerById($('participantSelect').value);if(!p){$('profileHint').textContent='';return}const missing=[];if(!p.lastName)missing.push('achternaam');if(!p.gender)missing.push('geslacht');if(p.rating==null||p.rating==='')missing.push('rating');$('profileHint').textContent=missing.length?`Je gegevens missen nog: ${missing.join(', ')}. Vraag de organisator dit aan te vullen.`:'Je gegevens zijn compleet.';}

async function getResponses(date){const snap=await getDocs(collection(db,'playingDates',date,'responses'));const o={};snap.forEach(d=>o[d.id]=d.data());responses[date]=o;return o}
async function setResponse(date,pid,status,by='deelnemer'){await setDoc(doc(db,'playingDates',date,'responses',pid),{status,updatedAt:new Date().toISOString(),updatedBy:by},{merge:true});await log('Beschikbaarheid gewijzigd',`${displayName(playerById(pid))}: ${status} voor ${date}`);renderParticipantDates();if($('orgDate').value===date)renderOrganizer();}
async function renderParticipantDates(){const pid=$('participantSelect').value||localStorage.getItem('selectedPlayer')||'';if(pid&&!$('participantSelect').value&&players.some(p=>p.id===pid))$('participantSelect').value=pid;const dates=upcomingTuesdays();const box=$('upcomingParticipant');box.innerHTML='';for(const date of dates){const r=await getResponses(date);const mine=r[pid]?.status||'';const groups={yes:[],no:[],none:[]};players.forEach(p=>groups[r[p.id]?.status||'none'].push(displayName(p)));const div=document.createElement('div');div.className='date-card';div.innerHTML=`<div class="row between"><strong>${esc(localDate(date))}</strong><span>${groups.yes.length} aangemeld</span></div><div class="status-buttons"><button class="${mine==='yes'?'':'off'}" data-s="yes">✓ Ik doe mee</button><button class="${mine==='no'?'danger':'off'}" data-s="no">✕ Ik kan niet</button></div><div class="people-groups"><div class="group"><b>🟢 Aangemeld (${groups.yes.length})</b>${groups.yes.map(esc).join(', ')||'—'}</div><div class="group"><b>🔴 Kan niet (${groups.no.length})</b>${groups.no.map(esc).join(', ')||'—'}</div><div class="group"><b>⚪ Geen reactie (${groups.none.length})</b>${groups.none.map(esc).join(', ')||'—'}</div></div>`;div.querySelectorAll('[data-s]').forEach(b=>b.onclick=()=>pid?setResponse(date,pid,b.dataset.s):toast('Kies eerst je naam'));box.append(div);}}

async function loadOrganizerDate(){const date=$('orgDate').value;if(!date)return;const ev=await getDoc(doc(db,'playingDates',date));evenings[date]=ev.exists()?ev.data():{courts:5};$('courtCount').value=evenings[date].courts||5;updateMaxPlayers();field=evenings[date].field||{playing:[],reserve:[]};currentSchedule=evenings[date].schedule||null;await getResponses(date);renderOrganizer();}
$('orgDate').onchange=loadOrganizerDate;$('courtCount').oninput=updateMaxPlayers;
function updateMaxPlayers(){$('maxPlayers').value=Number($('courtCount').value||5)*4}
$('saveEveningBtn').onclick=async()=>{const date=$('orgDate').value,courts=Math.max(1,Number($('courtCount').value)||5);await setDoc(doc(db,'playingDates',date),{courts,updatedAt:new Date().toISOString()},{merge:true});evenings[date]={...(evenings[date]||{}),courts};updateMaxPlayers();toast('Opgeslagen');log('Speelavond aangepast',`${date}: ${courts} banen`)};

function summaryCounts(date){const r=responses[date]||{},yes=players.filter(p=>r[p.id]?.status==='yes').length,no=players.filter(p=>r[p.id]?.status==='no').length;return {yes,no,none:players.length-yes-no,reserve:field.reserve.length}}
function renderOrganizer(){if(!$('orgDate').value)return;const date=$('orgDate').value,r=responses[date]||{},c=summaryCounts(date);$('organizerSummary').innerHTML=[['Aangemeld',c.yes],['Reserve',c.reserve],['Afwezig',c.no],['Geen reactie',c.none]].map(([l,n])=>`<div class="summary"><strong>${n}</strong>${l}</div>`).join('');$('organizerResponses').innerHTML=players.map(p=>`<div class="person-row"><div><b>${esc(displayName(p))}</b><div class="person-meta">nr. ${p.number||'-'} · rating ${p.rating??'-'}</div></div><div class="mini-actions"><button class="${r[p.id]?.status==='yes'?'':'secondary'}" data-p="${p.id}" data-s="yes">Ja</button><button class="${r[p.id]?.status==='no'?'danger':'secondary'}" data-p="${p.id}" data-s="no">Nee</button><button class="secondary" data-p="${p.id}" data-s="">—</button></div></div>`).join('')||'<p>Nog geen spelers.</p>';$('organizerResponses').querySelectorAll('[data-p]').forEach(b=>b.onclick=async()=>{if(b.dataset.s)await setResponse(date,b.dataset.p,b.dataset.s,'organisator');else{await deleteDoc(doc(db,'playingDates',date,'responses',b.dataset.p));await getResponses(date);renderOrganizer();}});renderField();renderSchedule();renderStatistics();renderLogs();}

$('proposeFieldBtn').onclick=async()=>{const date=$('orgDate').value,r=responses[date]||await getResponses(date),max=(Number($('courtCount').value)||5)*4;let yes=players.filter(p=>r[p.id]?.status==='yes');yes.sort((a,b)=>(a.reserveCount||0)-(b.reserveCount||0)||(a.lastPlayed||'').localeCompare(b.lastPlayed||''));field={playing:yes.slice(0,Math.floor(Math.min(yes.length,max)/4)*4).map(p=>p.id),reserve:yes.slice(Math.floor(Math.min(yes.length,max)/4)*4).map(p=>p.id)};await saveField();};
async function saveField(){const date=$('orgDate').value;await setDoc(doc(db,'playingDates',date),{field},{merge:true});renderField();renderOrganizer();}
function renderField(){const item=(id,target)=>{const p=playerById(id);return p?`<div class="move-item"><span>${esc(displayName(p))}</span><button class="secondary" data-id="${id}" data-target="${target}">${target==='reserve'?'Naar reserve':'Laat spelen'}</button></div>`:''};$('playingList').innerHTML=field.playing.map(id=>item(id,'reserve')).join('')||'<span class="hint">Nog geen voorstel</span>';$('reserveList').innerHTML=field.reserve.map(id=>item(id,'playing')).join('')||'<span class="hint">Geen reserves</span>';document.querySelectorAll('.move-item button').forEach(b=>b.onclick=async()=>{const from=b.dataset.target==='reserve'?'playing':'reserve',to=b.dataset.target;field[from]=field[from].filter(x=>x!==b.dataset.id);field[to].push(b.dataset.id);const max=(Number($('courtCount').value)||5)*4;if(field.playing.length>max){toast('Meer spelers dan beschikbare plaatsen');}await saveField();});}

function scoreTeam(a,b,c,d){const rating=x=>Number(x.rating??6);return Math.abs((rating(a)+rating(b))-(rating(c)+rating(d)));}
function bestMatch(group){const [a,b,c,d]=group;const opts=[[[a,b],[c,d]],[[a,c],[b,d]],[[a,d],[b,c]]];opts.sort((x,y)=>Math.abs(x[0].reduce((s,p)=>s+Number(p.rating??6),0)-x[1].reduce((s,p)=>s+Number(p.rating??6),0))-Math.abs(y[0].reduce((s,p)=>s+Number(p.rating??6),0)-y[1].reduce((s,p)=>s+Number(p.rating??6),0)));return opts[0]}
function buildRounds(ps,courts){const count=Math.min(ps.length,courts*4),selected=ps.slice(0,count),rounds=[];for(let round=0;round<2;round++){const rotated=round===0?selected:[...selected.slice(2),...selected.slice(0,2)];const matches=[];for(let i=0;i<rotated.length;i+=4){const g=rotated.slice(i,i+4);if(g.length<4)continue;const women=g.filter(p=>p.gender==='Vrouw');let teams=bestMatch(g);if(women.length===2){const men=g.filter(p=>p.gender!=='Vrouw');teams=[[women[0],men[0]],[women[1],men[1]]];}matches.push({court:i/4+1,teams});}rounds.push(matches);}return rounds;}
$('generateScheduleBtn').onclick=async()=>{if(field.playing.length<4){toast('Maak eerst een deelnemersveld');return}const ps=field.playing.map(playerById).filter(Boolean);currentSchedule={rounds:buildRounds(ps,Number($('courtCount').value)||5),createdAt:new Date().toISOString(),manual:false};await setDoc(doc(db,'playingDates',$('orgDate').value),{schedule:currentSchedule},{merge:true});log('Indeling gemaakt',$('orgDate').value);renderSchedule();};
$('manualScheduleBtn').onclick=async()=>{if(field.playing.length<4){toast('Maak eerst een deelnemersveld');return}const names=field.playing.map(id=>displayName(playerById(id))).join('\n');const text=prompt('Zet de spelers in gewenste volgorde, één naam per regel. Iedere vier vormen een baan:',names);if(!text)return;const ordered=text.split(/\n/).map(x=>x.trim()).map(n=>players.find(p=>displayName(p)===n||fullName(p)===n)).filter(Boolean);currentSchedule={rounds:buildRounds(ordered,Number($('courtCount').value)||5),createdAt:new Date().toISOString(),manual:true};await setDoc(doc(db,'playingDates',$('orgDate').value),{schedule:currentSchedule},{merge:true});renderSchedule();};
function renderSchedule(){if(!currentSchedule){$('scheduleOutput').innerHTML='';return}$('scheduleOutput').innerHTML=currentSchedule.rounds.map((round,ri)=>`<div class="schedule-round"><h3>Tiebreak ${ri+1} — spelers wisselen van baan</h3>${round.map(m=>`<div class="court"><b>Baan ${m.court}</b><br>${esc(displayName(m.teams[0][0]))} & ${esc(displayName(m.teams[0][1]))}<br>tegen<br>${esc(displayName(m.teams[1][0]))} & ${esc(displayName(m.teams[1][1]))}</div>`).join('')}</div>`).join('');}

function missingDetails(p){const a=[];if(!p.lastName)a.push('achternaam');if(!p.gender)a.push('geslacht');if(p.rating==null||p.rating==='')a.push('KNLTB-dubbelrating');return a}
function waText(type){const date=$('orgDate').value,fd=localDate(date),time='20:00–21:30',c=summaryCounts(date),max=(Number($('courtCount').value)||5)*4,spots=Math.max(0,max-c.yes);if(type==='invite')return `🎾 *Tiebreak-opstelling*\n\n📅 ${fd}\n🕗 ${time}\n\nKun je meedoen? Geef je beschikbaarheid door in de app:\n${APP_URL}`;if(type==='spots')return `🎾 *Nog spelers gezocht*\n\nVoor ${fd} zijn nog ${spots} ${spots===1?'plek':'plekken'} beschikbaar.\n🕗 ${time}\n\nMeld je aan via:\n${APP_URL}`;if(type==='urgent')return `🚨 *Dringend invaller gezocht*\n\nVoor ${fd} is op het laatste moment een plek vrijgekomen.\n🕗 ${time}\n\nWie kan meespelen?\n${APP_URL}`;if(type==='reminder'){const none=players.filter(p=>!(responses[date]||{})[p.id]).map(displayName);return `🔔 *Herinnering Tiebreak-opstelling*\n\nVoor ${fd} hebben de volgende spelers nog niet gereageerd:\n${none.map(n=>'• '+n).join('\n')||'Iedereen heeft gereageerd.'}\n\nApp: ${APP_URL}`;}if(type==='details'){const miss=players.filter(p=>missingDetails(p).length);return `🎾 *Gegevens aanvullen*\n\nWil je controleren of je gegevens in de Tiebreak-opstelling-app compleet zijn?\n\nNog niet compleet:\n${miss.map(p=>`• ${displayName(p)}: ${missingDetails(p).join(', ')}`).join('\n')||'Alle gegevens zijn compleet.'}\n\nOpen de app:\n${APP_URL}`;}if(type==='schedule'){if(!currentSchedule)return 'Maak eerst een definitieve indeling.';let t=`🎾 *Tiebreak-opstelling*\n\n📅 ${fd}\n🕗 ${time}`;currentSchedule.rounds.forEach((r,i)=>{t+=`\n\n*Tiebreak ${i+1}*`;r.forEach(m=>t+=`\nBaan ${m.court}: ${displayName(m.teams[0][0])} & ${displayName(m.teams[0][1])} tegen ${displayName(m.teams[1][0])} & ${displayName(m.teams[1][1])}`)});if(field.reserve.length)t+=`\n\n*Reserve:* ${field.reserve.map(id=>displayName(playerById(id))).join(', ')}`;return t;}return ''}
let waCurrent='';document.querySelectorAll('[data-wa]').forEach(b=>b.onclick=()=>{waCurrent=waText(b.dataset.wa);$('waPreview').value=waCurrent;$('waModal').classList.remove('hidden')});$('closeWaBtn').onclick=()=>$('waModal').classList.add('hidden');$('openWaBtn').onclick=()=>window.open('https://wa.me/?text='+encodeURIComponent($('waPreview').value),'_blank');$('copyWaBtn').onclick=async()=>{await navigator.clipboard.writeText($('waPreview').value);toast('Gekopieerd')};

function nextNumber(){return Math.max(0,...players.map(p=>Number(p.number)||0))+1}
$('savePlayerBtn').onclick=async()=>{const id=$('editPlayerId').value,data={firstName:$('firstName').value.trim(),lastName:$('lastName').value.trim(),gender:$('gender').value,rating:$('rating').value?Number($('rating').value):null};if(!data.firstName){toast('Voornaam is verplicht');return}if(id){await updateDoc(doc(db,'players',id),data);log('Speler gewijzigd',fullName(data))}else{data.number=nextNumber();data.createdAt=new Date().toISOString();await addDoc(collection(db,'players'),data);log('Speler toegevoegd',fullName(data))}clearPlayerForm()};
function clearPlayerForm(){$('editPlayerId').value='';['firstName','lastName','rating'].forEach(id=>$(id).value='');$('gender').value='';$('cancelEditBtn').classList.add('hidden')}$('cancelEditBtn').onclick=clearPlayerForm;
function renderPlayers(){$('playersList').innerHTML=players.map(p=>`<div class="person-row"><div><b>${p.number}. ${esc(fullName(p))}</b><div class="person-meta">${p.gender||'geslacht leeg'} · rating ${p.rating??'leeg'}</div></div><div class="mini-actions"><button data-edit="${p.id}">Wijzig</button><button class="danger" data-del="${p.id}">Wis</button><button class="secondary" data-request="${p.id}">WhatsApp</button></div></div>`).join('');document.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>{const p=playerById(b.dataset.edit);$('editPlayerId').value=p.id;$('firstName').value=p.firstName||'';$('lastName').value=p.lastName||'';$('gender').value=p.gender||'';$('rating').value=p.rating??'';$('cancelEditBtn').classList.remove('hidden');scrollTo({top:0,behavior:'smooth'})});document.querySelectorAll('[data-del]').forEach(b=>b.onclick=async()=>{const p=playerById(b.dataset.del);if(confirm(`${fullName(p)} verwijderen?`)){await deleteDoc(doc(db,'players',p.id));log('Speler verwijderd',fullName(p))}});document.querySelectorAll('[data-request]').forEach(b=>b.onclick=()=>{const p=playerById(b.dataset.request);$('waPreview').value=`🎾 *Tiebreak-opstelling*\n\nHoi ${p.firstName},\n\nWil je je gegevens in de app nog even aanvullen?\nWe missen: ${missingDetails(p).join(', ')||'geen gegevens'}.\n\nOpen de app:\n${APP_URL}`;$('waModal').classList.remove('hidden')});}

$('previewImportBtn').onclick=async()=>{importRows=[];const file=$('importFile').files[0];if(file){const buf=await file.arrayBuffer(),wb=XLSX.read(buf),ws=wb.Sheets[wb.SheetNames[0]],rows=XLSX.utils.sheet_to_json(ws,{defval:''});importRows=rows.map(r=>({firstName:r.Voornaam||r.voornaam||r.FirstName||'',lastName:r.Achternaam||r.achternaam||r.LastName||'',gender:r.Geslacht||r.geslacht||'',rating:r.Rating||r.rating||r['KNLTB-dubbelrating']||''}));}else{importRows=$('bulkText').value.split(/\r?\n/).filter(x=>x.trim()).map(line=>{const a=line.includes(';')?line.split(';'):line.trim().split(/\s+/,2);return {firstName:(a[0]||'').trim(),lastName:(a[1]||'').trim(),gender:(a[2]||'').trim(),rating:(a[3]||'').trim()}})}importRows=importRows.filter(r=>r.firstName);$('importPreview').innerHTML=`<div class="table-wrap"><table><tr><th>Voornaam</th><th>Achternaam</th><th>Geslacht</th><th>Rating</th></tr>${importRows.map(r=>`<tr><td>${esc(r.firstName)}</td><td>${esc(r.lastName)}</td><td>${esc(r.gender)}</td><td>${esc(r.rating)}</td></tr>`).join('')}</table></div>`;$('confirmImportBtn').disabled=!importRows.length};
$('confirmImportBtn').onclick=async()=>{const batch=writeBatch(db);let n=nextNumber();for(const r of importRows){const ref=doc(collection(db,'players'));batch.set(ref,{number:n++,firstName:r.firstName,lastName:r.lastName||'',gender:['Man','Vrouw'].includes(r.gender)?r.gender:'',rating:r.rating!==''&&Number.isFinite(Number(r.rating))?Number(r.rating):null,createdAt:new Date().toISOString()})}await batch.commit();toast(`${importRows.length} spelers geïmporteerd`);log('Bulkimport',`${importRows.length} spelers`);$('confirmImportBtn').disabled=true};

async function renderStatistics(){const rows=[];for(const p of players){let yes=0,no=0,res=0;for(const date of Object.keys(responses)){if(responses[date][p.id]?.status==='yes')yes++;if(responses[date][p.id]?.status==='no')no++;if((evenings[date]?.field?.reserve||[]).includes(p.id))res++;}rows.push({nr:p.number,naam:fullName(p),aangemeld:yes,afgemeld:no,reserve:res})}$('statistics').innerHTML=`<div class="table-wrap"><table><tr><th>Nr.</th><th>Speler</th><th>Aangemeld</th><th>Afgemeld</th><th>Reserve</th></tr>${rows.map(r=>`<tr><td>${r.nr}</td><td>${esc(r.naam)}</td><td>${r.aangemeld}</td><td>${r.afgemeld}</td><td>${r.reserve}</td></tr>`).join('')}</table></div>`;window.statRows=rows;}
function download(name,data,type='text/plain'){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([data],{type}));a.download=name;a.click();URL.revokeObjectURL(a.href)}
$('exportCsvBtn').onclick=()=>{const rows=window.statRows||[];download('tiebreak-statistieken.csv','Nr;Speler;Aangemeld;Afgemeld;Reserve\n'+rows.map(r=>`${r.nr};${r.naam};${r.aangemeld};${r.afgemeld};${r.reserve}`).join('\n'),'text/csv')};
$('exportXlsxBtn').onclick=()=>{const ws=XLSX.utils.json_to_sheet((window.statRows||[]).map(r=>({Nummer:r.nr,Speler:r.naam,Aangemeld:r.aangemeld,Afgemeld:r.afgemeld,Reserve:r.reserve}))),wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,ws,'Statistieken');XLSX.writeFile(wb,'tiebreak-statistieken.xlsx')};
$('backupBtn').onclick=async()=>{const data={exportedAt:new Date().toISOString(),players,evenings,responses};download('tiebreak-backup.json',JSON.stringify(data,null,2),'application/json')};
async function renderLogs(){try{const snap=await getDocs(query(collection(db,'logs'),orderBy('at','desc'),limit(30)));$('logbook').innerHTML=snap.docs.map(d=>{const x=d.data();return `<div class="person-row"><div><b>${esc(x.action)}</b><div class="person-meta">${esc(x.details||'')} · ${new Date(x.at).toLocaleString('nl-NL')}</div></div></div>`}).join('')||'<p class="hint">Nog geen logregels.</p>'}catch{$('logbook').innerHTML='<p class="hint">Logboek kan nog niet worden geladen.</p>'}}

$('refreshBtn').onclick=()=>location.reload();initTabs();renderDates();setTimeout(()=>{const saved=localStorage.getItem('selectedPlayer');if(saved&&players.some(p=>p.id===saved)){$('participantSelect').value=saved;renderParticipantDates()}},1000);
